#ifndef DEFINE_H_INCLUDED
#define DEFINE_H_INCLUDED


#define	ID_OGGI	    1
//SALTO IL 2 PERCHE' PER QUALCHE MOTIVO VIENE "TRIGGERATO" DAL TASTO ESC
#define	ID_DBASE	60
#define	ID_CALC 	3
#define	ID_GG    	4
#define	ID_MM    	5
#define	ID_AAAA    	6
#define	CLOCK    	7
#define	DATA    	8
#define OG_OK       9
#define GRUPPO      10
#define PULSENTR    11
#define PULSUSC     12
#define IMPORTO     13
#define MOTIVO      14
#define CATEG       15
#define C_BANCA_IN  16
#define ID_GEN      17
#define ID_MEN      18
#define ID_AEN      19
#define C_BANCA_OUT 20
#define ID_GUSC     21
#define ID_MUSC     22
#define ID_AUSC     23
#define SCRIVI      24
#define ANNUL       25
#define OG_VAI      26
#define DIETRO      27
#define AVANTI      28
#define OG_NOTE     29
#define SELDATO     30
#define SELBANCA    31
#define MOSTRADATO  32
#define OG_CANC     33
#define C_RIEPILOG  34
#define ANNOTAZ     35
#define GSETTIMANA  36
#define ID_FAIVED   37
#define ID_NONFARVBUT       38
#define ID_SOLNFARVBUT      39
#define ID_FAIVBUT          40
#define ID_SOLFAIVBUT       41
#define ID_TUTTEVIS         42
#define ID_CERCA            43
#define ID_TIMER            44
#define ID_ESTESO           45
#define ID_FOK              46
#define ID_IDENT            47
#define ID_GAPERTO          48
#define ID_MAPERTO          49
#define ID_AAPERTO          50
#define ID_GCHIUSO          51
#define ID_MCHIUSO          52
#define ID_ACHIUSO          53
#define ID_FINS             54
#define ID_FCAMB            55
#define ID_FCANC            56
#define ID_FANNUL           57
#define ID_POSTODI          58
#define ID_INIANNO          59
//IL 60 E' GIA' PRESO DA ID_BASE
#define ID_INIZIALE         61
#define ID_SCRISA           62
#define SELBANCA1           63
#define ID_GDA              64
#define ID_MDA              65
#define ID_ADA              66
#define ID_GA               67
#define ID_MA               68
#define ID_AA               69
#define C_CALCO             70
#define ELIGNUL             71
#define ELIENUL             72
#define ELIUNUL             73
#define ELITNUL             74
#define DOIT                75
#define C_RIEPRIS           76
#define C_RIEPILOG1         77
#define C_RIEPILOG2         78
#define C_RIEPILOG3         79
#define C_ORDRIS            80
#define C_ORDRIEP           81
#define C_ORDRIEP1          82
#define C_ORDRIEP2          83
#define C_ORDRIEP3          84
#define C_ASPETTA           85
#define C_DONE              86
#define NOTES               87
#define NOTE_OK             88
#define NOTE_ANN            89
#define NOTE_DATA           90


#endif // DEFINE_H_INCLUDED
